services:
  - type: web
    name: smart-attendance-system
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: bash build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: MONGODB_URI
        sync: false
